name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.1
homepage: https://github.com/xmany/GeoFlutterFire

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.7.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
